### ISSUE TITLE
Bug reported in Tutorial: Build a Basic CRUD App with Node.js

### ISSUE THREAD

**Issue by mraible** [oktadeveloper/okta-blog#18]
##### **Overview of the issue**

Issue reported: `Cannot read property 'length' of undefined`

From [a comment](http://disq.us/p/1y8yfck):

```
TypeError: D:\Shivam\Node\blog\views\index.pug:14
12| .posts
13| ul
> 14| each post in posts
15| .row
16| .offset-sm-2.col-sm-8
17| li

Cannot read property 'length' of undefined
at eval (eval at wrap (D:\Shivam\Node\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:80:32)
at eval (eval at wrap (D:\Shivam\Node\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:123:4)
at template (eval at wrap (D:\Shivam\Node\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:143:97)
at Object.exports.renderFile (D:\Shivam\Node\blog\node_modules\pug\lib\index.js:418:38)
at Object.exports.renderFile (D:\Shivam\Node\blog\node_modules\pug\lib\index.js:408:21)
at View.exports.__express [as engine] (D:\Shivam\Node\blog\node_modules\pug\lib\index.js:455:11)
at View.render (D:\Shivam\Node\blog\node_modules\express\lib\view.js:135:8)
at tryRender (D:\Shivam\Node\blog\node_modules\express\lib\application.js:640:10)
at Function.render (D:\Shivam\Node\blog\node_modules\express\lib\application.js:592:3)
at ServerResponse.render (D:\Shivam\Node\blog\node_modules\express\lib\response.js:1008:7)
```

**Comment by mraible** [comment]
Closing, duplicate of #16.
