### ISSUE TITLE
Unknown authentication strategy "oidc" in Tutorial: Build a Basic CRUD App with Node.js

### ISSUE THREAD

**Issue by mraible** [oktadeveloper/okta-blog#21]
##### **Overview of the issue**

Error [reported by abasiono udosen](http://disq.us/p/1tvx2s9), [twice](http://disq.us/p/1tw0erm):

```
Unknown authentication strategy "oidc"
Error: Unknown authentication strategy "oidc"
at attempt (/home/abaz/Documents/ngHP/blog/node_modules/passport/lib/middleware/authenticate.js:173:37)
at authenticate (/home/abaz/Documents/ngHP/blog/node_modules/passport/lib/middleware/authenticate.js:349:7)
at /home/abaz/Documents/ngHP/blog/node_modules/@okta/oidc-middleware/src/connectUtil.js:79:28
at Layer.handle [as handle_request] (/home/abaz/Documents/ngHP/blog/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/home/abaz/Documents/ngHP/blog/node_modules/express/lib/router/index.js:317:13)
at /home/abaz/Documents/ngHP/blog/node_modules/express/lib/router/index.js:284:7
at Function.process_params (/home/abaz/Documents/ngHP/blog/node_modules/express/lib/router/index.js:335:12)
at next (/home/abaz/Documents/ngHP/blog/node_modules/express/lib/router/index.js:275:10)
at urlencodedParser (/home/abaz/Documents/ngHP/blog/node_modules/body-parser/lib/types/urlencoded.js:91:7)
at Layer.handle [as handle_request] (/home/abaz/Documents/ngHP/blog/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/home/abaz/Documents/ngHP/blog/node_modules/express/lib/router/index.js:317:13)
at /home/abaz/Documents/ngHP/blog/node_modules/express/lib/router/index.js:284:7
at Function.process_params (/home/abaz/Documents/ngHP/blog/node_modules/express/lib/router/index.js:335:12)
at next (/home/abaz/Documents/ngHP/blog/node_modules/express/lib/router/index.js:275:10)
at SessionStrategy.strategy.pass (/home/abaz/Documents/ngHP/blog/node_modules/passport/lib/middleware/authenticate.js:325:9)
at SessionStrategy.authenticate (/home/abaz/Documents/ngHP/blog/node_modules/passport/lib/strategies/session.js:71:10)
at attempt (/home/abaz/Documents/ngHP/blog/node_modules/passport/lib/middleware/authenticate.js:348:16)
at authenticate (/home/abaz/Documents/ngHP/blog/node_modules/passport/lib/middleware/authenticate.js:349:7)
at Layer.handle [as handle_request] (/home/abaz/Documents/ngHP/blog/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/home/abaz/Documents/ngHP/blog/node_modules/express/lib/router/index.js:317:13)
at /home/abaz/Documents/ngHP/blog/node_modules/express/lib/router/index.js:284:7
at Function.process_params (/home/abaz/Documents/ngHP/blog/node_modules/express/lib/router/index.js:335:12)
```

**Comment by rafakwolf** [comment]
same issue here, using the sample app https://github.com/oktadeveloper/okta-node-express-15-minute-auth-example

**Comment by rdegges** [comment]
This is related to the npm install not working. It can be fixed by re-running the npm install commands (maybe they failed due to npm outage, internet being flaky, etc.). I tried this a bunch of times in a shell script and the only time it failed was when the npm install didn't work :(
